### ISSUE TITLE
Give up?

### ISSUE THREAD

**Issue by Mutim** [PerceiveDev/PlayerHousing#2]
You realize that if you made something like hypixels plugin, with player housing, with in the config you can add your own schematic files, you could sell it for 10-20 dollars (I would pay that) But it would have to be good. Don't give up. If it gets hard, keep pressing. If you need more knowledge, learn more. But don't give up. It just makes it that much easier the next time. Maybe borrow some of the code for ASkyBlock for the plot generation, and just make it so that houses are like 500 blocks apart from center to center. It grabs the schem file, and places it at the +x +z axis on the center point on the grid. From there, the plugin looks for a beacon on island generation, and sets the spawn at that point -1 (to account for the block, you know). And direction is always going to be north. But, i think you guys have this. I have been looking around, and you're the only one who said "me and my team are going to tackle this!" So, what are you waiting for?! Do it! Don't quit!

**Comment by foxfirecodes** [comment]
[I already replied to this](https://github.com/PerceiveDev/PlayerHousing/issues/1#issuecomment-287076191) in #1.
